twig:
    # Default directory for Twig templates in this bundle.
    default_path: '%kernel.project_dir%/src/Resources/views'

    # Registers the bundle's templates so they can be referenced using "@HelloWorldBundle" in the main application.
    paths:
        '%kernel.project_dir%/vendor/lodel/lodel-helloworld-bundle/src/Resources/views': HelloWorldBundle
