services:
    _defaults:
        autowire: false # Modify this if necessary to enable autowiring for services
        autoconfigure: false # Modify this if necessary to enable autoconfiguration for services
        public: false # Modify this if necessary to change service visibility

    # Definition for the HelloWorldSubscriber service
    Lodel\HelloWorldBundle\EventSubscriber\HelloWorldSubscriber:
        arguments:
            $twig: '@twig'  # Injecting the Twig service
            $router: '@router'  # Injecting the Router service
        tags:
            - { name: 'kernel.event_subscriber' } # Tags this service as an event subscriber, so Symfony knows to register it for events.
